"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/client";
import { useToast } from "@/components/Toast";
import Link from "next/link";

type Аналитика = { totals: { sent: number; failed: number; bounced: number; unsubscribed: number; replies: number; conversions: number; revenue: number }; rates: { replyRate: number; conversionRate: number }; cohorts: Array<{ cohort: string; contacts: number; active: number; purchases: number; revenue: number; retentionRate: number; revenuePerContact: number }>; usage: { plan: string; period: string } };
export default function AnalyticsPage() { const { notify } = useToast(); const [analytics, setАналитика] = useState<Аналитика | null>(null); const [recommendations, setRecommendations] = useState<{ summary: string; recommendations: string[] } | null>(null); useEffect(() => { api<{ analytics: Аналитика }>("/api/analytics/summary").then((result) => setАналитика(result.analytics)).catch((error) => notify(error instanceof Error ? error.message : "Аналитика failed", "error")); }, [notify]); const loadRecommendations = async () => { try { const result = await api<{ recommendations: typeof recommendations }>("/api/analytics/recommendations", { method: "POST" }); setRecommendations(result.recommendations); } catch (error) { notify(error instanceof Error ? error.message : "Не удалось получить рекомендации", "error"); } }; if (!analytics) return <div className="empty">Загрузка аналитики...</div>; const totals = analytics.totals; return <div><div className="page-head"><div><h1 className="page-title">Аналитика</h1><p className="page-sub">Результаты кампаний, когорты и выручка.</p></div><Link href="/" className="btn">Главная</Link></div><div className="metric-grid"><Metric label="Отправлено" value={totals.sent} /><Metric label="Ответы" value={totals.replies} /><Metric label="Конверсии" value={totals.conversions} /><Metric label="Выручка" value={totals.revenue.toFixed(2)} /><Metric label="Доля ответов" value={`${analytics.rates.replyRate}%`} /><Metric label="Доля конверсий" value={`${analytics.rates.conversionRate}%`} /></div><section className="card" style={{ padding: 18, marginTop: 20 }}><div className="row"><div className="section-label grow">Рекомендации ИИ по оптимизации</div><button className="btn btn-primary btn-sm" onClick={loadRecommendations}>Анализировать</button></div>{recommendations && <><p className="small">{recommendations.summary}</p><ul className="small">{recommendations.recommendations.map((item) => <li key={item}>{item}</li>)}</ul></>}</section><section className="card" style={{ padding: 18, marginTop: 20 }}><div className="row"><div className="section-label grow">Cohorts and revenue</div><span className="badge blue">{analytics.usage.plan} · {analytics.usage.period}</span></div>{analytics.cohorts.length === 0 ? <div className="empty">No cohort events yet.</div> : <div className="stack" style={{ gap: 7, marginTop: 10 }}>{analytics.cohorts.map((cohort) => <div className="row small" key={cohort.cohort}><span className="grow">{cohort.cohort}</span><span>{cohort.contacts} contacts</span><span>{cohort.retentionRate}% retention</span><span>{cohort.purchases} purchases</span><span>{cohort.revenue.toFixed(2)} revenue</span><span>{cohort.revenuePerContact.toFixed(2)}/contact</span></div>)}</div>}</section></div>; }
function Metric({ label, value }: { label: string; value: number | string }) { return <div className="kpi"><div className="label">{label}</div><div className="value">{value}</div></div>; }
