import { randomBytes } from "node:crypto";
import { z } from "zod";
import { getApiUser, handleError, ok, readJson, unauthorized, badRequest } from "@/lib/api";
import { encryptCredentials } from "@/lib/crypto";
import { prisma } from "@/lib/prisma";

const schema = z.object({ provider: z.enum(["shopify", "woocommerce"]), name: z.string().trim().min(1).max(120), secret: z.string().min(16).max(500) });
export async function GET(req: Request) { try { const user = await getApiUser(); if (!user) return unauthorized(); const url = new URL(req.url); const limit = parseLimit(url.searchParams.get("limit")); const cursorValue = url.searchParams.get("cursor"); const cursor = cursorValue ? parseCursor(cursorValue) : null; if (cursorValue && !cursor) return badRequest("Invalid cursor"); const rows = await prisma.integrationConnection.findMany({ where: { userId: user.id, ...(cursor ? { OR: [{ createdAt: { lt: cursor.createdAt } }, { createdAt: cursor.createdAt, id: { lt: cursor.id } }] } : {}) }, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: limit + 1 }); const hasMore = rows.length > limit; const integrations = (hasMore ? rows.slice(0, limit) : rows); const last = integrations.at(-1); const nextCursor = hasMore && last ? encodeCursor({ createdAt: last.createdAt.toISOString(), id: last.id }) : null; return ok({ integrations: integrations.map((item) => ({ id: item.id, provider: item.provider, name: item.name, publicToken: item.publicToken, status: item.status, eventCount: item.eventCount, lastEventAt: item.lastEventAt?.toISOString() ?? null, lastError: item.lastError, createdAt: item.createdAt.toISOString() })), nextCursor, hasMore }); } catch (error) { return handleError(error); } }

function parseLimit(value: string | null): number { const parsed = Number(value ?? 50); return Number.isInteger(parsed) ? Math.max(1, Math.min(100, parsed)) : 50; }
function encodeCursor(cursor: { createdAt: string; id: string }): string { return Buffer.from(JSON.stringify(cursor), "utf8").toString("base64url"); }
function parseCursor(value: string): { createdAt: Date; id: string } | null { try { const parsed = JSON.parse(Buffer.from(value, "base64url").toString("utf8")) as { createdAt?: unknown; id?: unknown }; if (typeof parsed.createdAt !== "string" || typeof parsed.id !== "string" || !parsed.id) return null; const createdAt = new Date(parsed.createdAt); return Number.isNaN(createdAt.getTime()) ? null : { createdAt, id: parsed.id }; } catch { return null; } }
export async function POST(req: Request) { try { const user = await getApiUser(); if (!user) return unauthorized(); const data = schema.parse(await readJson(req)); const publicToken = `int_${randomBytes(18).toString("base64url")}`; const integration = await prisma.integrationConnection.create({ data: { userId: user.id, provider: data.provider, name: data.name, publicToken, secretEncrypted: encryptCredentials(data.secret), webhookSecretEncrypted: data.provider === "shopify" ? encryptCredentials(data.secret) : null } }); return ok({ integration: { id: integration.id, provider: integration.provider, name: integration.name, publicToken: integration.publicToken, status: integration.status, hasWebhookSecret: Boolean(integration.webhookSecretEncrypted) }, webhookUrl: `${process.env.APP_URL ?? "http://localhost:3000"}/api/integrations/${publicToken}/events` }, 201); } catch (error) { return handleError(error); } }
export async function DELETE(req: Request) { try { const user = await getApiUser(); if (!user) return unauthorized(); const id = new URL(req.url).searchParams.get("id"); if (!id) return badRequest("id is required"); await prisma.integrationConnection.deleteMany({ where: { id, userId: user.id } }); return ok({ deleted: true }); } catch (error) { return handleError(error); } }
