import { randomBytes } from "node:crypto";
import { z } from "zod";
import { getApiUser, handleError, ok, readJson, unauthorized, badRequest } from "@/lib/api";
import { encryptCredentials } from "@/lib/crypto";
import { prisma } from "@/lib/prisma";

const schema = z.object({ provider: z.enum(["shopify", "woocommerce"]), name: z.string().trim().min(1).max(120), secret: z.string().min(16).max(500) });
export async function GET() { try { const user = await getApiUser(); if (!user) return unauthorized(); const integrations = await prisma.integrationConnection.findMany({ where: { userId: user.id }, orderBy: { createdAt: "desc" } }); return ok({ integrations: integrations.map((item) => ({ id: item.id, provider: item.provider, name: item.name, publicToken: item.publicToken, status: item.status, eventCount: item.eventCount, lastEventAt: item.lastEventAt?.toISOString() ?? null, lastError: item.lastError, createdAt: item.createdAt.toISOString() })) }); } catch (error) { return handleError(error); } }
export async function POST(req: Request) { try { const user = await getApiUser(); if (!user) return unauthorized(); const data = schema.parse(await readJson(req)); const publicToken = `int_${randomBytes(18).toString("base64url")}`; const integration = await prisma.integrationConnection.create({ data: { userId: user.id, provider: data.provider, name: data.name, publicToken, secretEncrypted: encryptCredentials(data.secret), webhookSecretEncrypted: data.provider === "shopify" ? encryptCredentials(data.secret) : null } }); return ok({ integration: { id: integration.id, provider: integration.provider, name: integration.name, publicToken: integration.publicToken, status: integration.status, hasWebhookSecret: Boolean(integration.webhookSecretEncrypted) }, webhookUrl: `${process.env.APP_URL ?? "http://localhost:3000"}/api/integrations/${publicToken}/events` }, 201); } catch (error) { return handleError(error); } }
export async function DELETE(req: Request) { try { const user = await getApiUser(); if (!user) return unauthorized(); const id = new URL(req.url).searchParams.get("id"); if (!id) return badRequest("id is required"); await prisma.integrationConnection.deleteMany({ where: { id, userId: user.id } }); return ok({ deleted: true }); } catch (error) { return handleError(error); } }
